### ISSUE TITLE
Name as you'd like it to appear in Racket v8.10 release notes?

### ISSUE THREAD

**Issue by jbclements** [paperclipmaximizer/paperclipmaximizer#1]
Hi there! Please excuse my out-of-band use of github issues as a means of contacting you. I'm putting together the Racket v8.10 release notes, and I'm hoping to include you in the list of contributors. How would you like your name to appear? You can also let me know by sending me email at clements@racket-lang.org .

**Comment by paperclipmaximizer** [comment]
That sounds great. I'll send you an email

**Comment by paperclipmaximizer** [comment]
Please list Liam Avella-Pisera as the name, if you can

**Comment by jbclements** [comment]
Ooh, release went out last night, might still be able to fix it.

**Comment by jbclements** [comment]
feel free to close this issue!

**Comment by paperclipmaximizer** [comment]
Thankyou!
